name: release
on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  BINDLE_SERVER_URL: <%= serverUrl %>
  HIPPO_SERVICE_URL: <%= hippoUrl %>

jobs:
  publish:
    name: Build and publish release assets

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust bits
      run: rustup target add wasm32-wasi

    - name: Set the release version (tag)
      if: startsWith(github.ref, 'refs/tags/v')
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Set the release version (main)
      if: github.ref == 'refs/heads/main'
      shell: bash
      run: echo "RELEASE_VERSION=canary" >> $GITHUB_ENV

    - name: Build release
      run: cargo build --verbose --target wasm32-wasi --release

    - name: Install hippofactory
      run: |
        mkdir -p tools/tmp
        wget https://github.com/deislabs/hippofactory/releases/download/v0.4.0/hippofactory-v0.4.0-linux-amd64.tar.gz -q -O ./tools/tmp/hippofactory.tar.gz
        tar xf ./tools/tmp/hippofactory.tar.gz -C ./tools

    - name: Publish bindle (tagged)
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        HIPPO_USERNAME: ${{ secrets.HIPPO_USERNAME }}
        HIPPO_PASSWORD: ${{ secrets.HIPPO_PASSWORD }}
      run: ./tools/hippofactory . -v production -o message

    - name: Publish bindle (main)
      if: github.ref == 'refs/heads/main'
      env:
        HIPPO_USERNAME: ${{ secrets.HIPPO_USERNAME }}
        HIPPO_PASSWORD: ${{ secrets.HIPPO_PASSWORD }}
      run: USER=canary ./tools/hippofactory . -o message
